metadata:
  name: default
  version: 1.0.0
  description: Default RxDx seed data with example users and workitems for development and testing
  author: RxDx Team

settings:
  default_password: password123

users:
  - id: "00000000-0000-0000-0000-000000000001"
    email: admin@rxdx.example.com
    full_name: System Administrator
    role: admin
    is_active: true

  - id: "00000000-0000-0000-0000-000000000002"
    email: pm@rxdx.example.com
    full_name: Project Manager
    role: project_manager
    is_active: true

  - id: "00000000-0000-0000-0000-000000000003"
    email: validator@rxdx.example.com
    full_name: Quality Validator
    role: validator
    is_active: true

  - id: "00000000-0000-0000-0000-000000000004"
    email: auditor@rxdx.example.com
    full_name: Compliance Auditor
    role: auditor
    is_active: true

  - id: "00000000-0000-0000-0000-000000000005"
    email: developer@rxdx.example.com
    full_name: Software Developer
    role: user
    is_active: true

  - id: "00000000-0000-0000-0000-000000000006"
    email: tester@rxdx.example.com
    full_name: QA Tester
    role: user
    is_active: true

  - id: "00000000-0000-0000-0000-000000000007"
    email: inactive@rxdx.example.com
    full_name: Inactive User
    role: user
    is_active: false

workitems:
  requirements:
    - id: "10000000-0000-0000-0000-000000000001"
      title: User Authentication System
      description: The system shall provide secure user authentication using industry-standard protocols
      status: active
      priority: 5
      acceptance_criteria: Given a valid user credential, when the user attempts to login, then the system shall authenticate and provide a JWT token
      business_value: Ensures secure access to the system and protects sensitive data
      source: security
      created_by: "00000000-0000-0000-0000-000000000002"

    - id: "10000000-0000-0000-0000-000000000002"
      title: Role-Based Access Control
      description: The system shall implement RBAC with predefined roles - admin, project_manager, validator, auditor, user
      status: active
      priority: 5
      acceptance_criteria: Given a user with a specific role, when accessing a protected resource, then the system shall grant or deny access based on role permissions
      business_value: Provides granular access control for regulatory compliance
      source: compliance
      created_by: "00000000-0000-0000-0000-000000000002"

    - id: "10000000-0000-0000-0000-000000000003"
      title: Audit Trail Logging
      description: The system shall maintain an immutable audit trail of all user actions for compliance purposes
      status: active
      priority: 4
      acceptance_criteria: Given any user action, when the action is performed, then the system shall create an immutable audit log entry with timestamp, user, and action details
      business_value: Enables regulatory compliance and forensic analysis
      source: regulation
      created_by: "00000000-0000-0000-0000-000000000002"

    - id: "10000000-0000-0000-0000-000000000004"
      title: Digital Signature Support
      description: The system shall support cryptographic digital signatures for document approval workflows
      status: draft
      priority: 4
      acceptance_criteria: Given a document requiring approval, when an authorized user signs it, then the system shall create a cryptographic signature that can be verified
      business_value: Provides non-repudiation for regulatory document approval
      source: compliance
      created_by: "00000000-0000-0000-0000-000000000002"

  tasks:
    - id: "20000000-0000-0000-0000-000000000001"
      title: Implement JWT Authentication
      description: Implement JWT-based authentication with access and refresh tokens
      status: completed
      priority: 5
      estimated_hours: 16
      actual_hours: 14
      assigned_to: "00000000-0000-0000-0000-000000000005"
      created_by: "00000000-0000-0000-0000-000000000002"

    - id: "20000000-0000-0000-0000-000000000002"
      title: Create User Management API
      description: Develop REST API endpoints for user CRUD operations
      status: active
      priority: 4
      estimated_hours: 24
      actual_hours: 8
      assigned_to: "00000000-0000-0000-0000-000000000005"
      created_by: "00000000-0000-0000-0000-000000000002"

    - id: "20000000-0000-0000-0000-000000000003"
      title: Implement Audit Logging Service
      description: Create audit logging service with immutable log storage
      status: draft
      priority: 4
      estimated_hours: 20
      assigned_to: "00000000-0000-0000-0000-000000000005"
      created_by: "00000000-0000-0000-0000-000000000002"

  tests:
    - id: "30000000-0000-0000-0000-000000000001"
      title: Test User Login Success
      description: Verify successful user login with valid credentials
      status: active
      priority: 5
      test_type: integration
      test_steps: |
        1. Navigate to login page
        2. Enter valid email
        3. Enter valid password
        4. Click login button
      expected_result: User is authenticated and redirected to dashboard
      test_status: passed
      assigned_to: "00000000-0000-0000-0000-000000000006"
      created_by: "00000000-0000-0000-0000-000000000003"

    - id: "30000000-0000-0000-0000-000000000002"
      title: Test Invalid Login Attempt
      description: Verify system rejects invalid credentials
      status: active
      priority: 5
      test_type: integration
      test_steps: |
        1. Navigate to login page
        2. Enter invalid email
        3. Enter any password
        4. Click login button
      expected_result: User sees error message and is not authenticated
      test_status: passed
      assigned_to: "00000000-0000-0000-0000-000000000006"
      created_by: "00000000-0000-0000-0000-000000000003"

    - id: "30000000-0000-0000-0000-000000000003"
      title: Test Account Lockout
      description: Verify account lockout after 3 failed login attempts
      status: active
      priority: 4
      test_type: security
      test_steps: |
        1. Attempt login with wrong password 3 times
        2. Verify account is locked
        3. Wait for lockout period
        4. Verify account is unlocked
      expected_result: Account is locked after 3 failed attempts and unlocks after timeout
      test_status: not_run
      assigned_to: "00000000-0000-0000-0000-000000000006"
      created_by: "00000000-0000-0000-0000-000000000003"

  risks:
    - id: "40000000-0000-0000-0000-000000000001"
      title: Unauthorized Access Risk
      description: Risk of unauthorized users gaining access to sensitive data
      status: assessed
      priority: 5
      severity: 9
      occurrence: 3
      detection: 2
      mitigation_actions: Implement MFA, regular security audits, intrusion detection
      risk_owner: "00000000-0000-0000-0000-000000000001"
      created_by: "00000000-0000-0000-0000-000000000002"

    - id: "40000000-0000-0000-0000-000000000002"
      title: Data Integrity Risk
      description: Risk of data corruption or unauthorized modification
      status: assessed
      priority: 4
      severity: 8
      occurrence: 2
      detection: 3
      mitigation_actions: Implement checksums, audit logging, backup procedures
      risk_owner: "00000000-0000-0000-0000-000000000001"
      created_by: "00000000-0000-0000-0000-000000000002"

relationships:
  # Tasks implement Requirements
  - from_id: "20000000-0000-0000-0000-000000000001"
    to_id: "10000000-0000-0000-0000-000000000001"
    type: IMPLEMENTS

  - from_id: "20000000-0000-0000-0000-000000000002"
    to_id: "10000000-0000-0000-0000-000000000001"
    type: IMPLEMENTS

  - from_id: "20000000-0000-0000-0000-000000000003"
    to_id: "10000000-0000-0000-0000-000000000003"
    type: IMPLEMENTS

  # Requirements tested by Tests
  - from_id: "10000000-0000-0000-0000-000000000001"
    to_id: "30000000-0000-0000-0000-000000000001"
    type: TESTED_BY

  - from_id: "10000000-0000-0000-0000-000000000001"
    to_id: "30000000-0000-0000-0000-000000000002"
    type: TESTED_BY

  - from_id: "10000000-0000-0000-0000-000000000001"
    to_id: "30000000-0000-0000-0000-000000000003"
    type: TESTED_BY

  # Requirements mitigate Risks
  - from_id: "10000000-0000-0000-0000-000000000001"
    to_id: "40000000-0000-0000-0000-000000000001"
    type: MITIGATES

  - from_id: "10000000-0000-0000-0000-000000000002"
    to_id: "40000000-0000-0000-0000-000000000001"
    type: MITIGATES

  - from_id: "10000000-0000-0000-0000-000000000003"
    to_id: "40000000-0000-0000-0000-000000000002"
    type: MITIGATES

  # Requirement dependencies
  - from_id: "10000000-0000-0000-0000-000000000002"
    to_id: "10000000-0000-0000-0000-000000000001"
    type: DEPENDS_ON

  - from_id: "10000000-0000-0000-0000-000000000003"
    to_id: "10000000-0000-0000-0000-000000000001"
    type: DEPENDS_ON

  - from_id: "10000000-0000-0000-0000-000000000004"
    to_id: "10000000-0000-0000-0000-000000000001"
    type: DEPENDS_ON

  # Task dependencies
  - from_id: "20000000-0000-0000-0000-000000000002"
    to_id: "20000000-0000-0000-0000-000000000001"
    type: DEPENDS_ON
